export const COMPANY_SITES = [
  {
    name: 'Dubai Holding',
    url: 'https://dubaiholding.com/en/media-hub/press-releases/',
    articlePrependUrl: '',
    articleListSelector: 'div.summary-wrap > h4 > a',
    articleHeaderSelector: 'div.container > h2',
    articleDateSelector: 'div.container > strong',
    articleTextSelector: 'div.container > p',
    articleWriterSelector: '',
    hasWriter: false,
    hasHeader: true,
    hasDate: true,
  },
  {
    name: 'Dubai Duty Free',
    url: 'https://www.dubaidutyfree.com/media_center/news',
    articlePrependUrl: 'https://www.dubaidutyfree.com/', // Some hrefs need to be prepended
    articleListSelector: 'div.col-md-6.awards-blk > a.item-title',
    articleHeaderSelector: 'span.item-title',
    articleDateSelector: 'span.date',
    articleTextSelector: 'div.col-md-12.awards-details > p',
    articleWriterSelector: '',
    hasWriter: false,
    hasHeader: true,
    hasDate: true,
  },
  {
    name: 'du',
    url: 'http://www.du.ae/about-us/media-centre/news',
    articlePrependUrl: '',
    articleListSelector: 'div.media-content > p > a.press-release-title',
    articleHeaderSelector: 'h1.title.news-title',
    articleDateSelector: 'p.news-date',
    articleTextSelector: 'div.contentIn div:nth-child(6)',
    articleWriterSelector: '',
    hasWriter: false,
    hasHeader: true,
    hasDate: true,
  },
  {
    name: 'Al Futtaim',
    url: 'http://www.alfuttaim.com/home/mediacentre/News?className=AllNews&brandSelector=News&newscategory=AFGCorporate_design/MediaCentre/News/AllNews',
    articlePrependUrl: 'http://www.alfuttaim.com',
    articleListSelector: 'div.col-md-4.col-sm-6.col-xs-12 > a',
    articleHeaderSelector: 'h2.news-video-details__title',
    articleDateSelector: 'div.news-video-details__content__header',
    articleTextSelector: 'div.news-video-details__content__detail.Description > p',
    articleWriterSelector: '',
    hasWriter: false,
    hasHeader: true,
    hasDate: true,
  },
  {
    name: 'Dubai Electricity and Water Authority',
    url: 'https://www.dewa.gov.ae/en/about-dewa/news-and-media/press-and-news/latest-news',
    articlePrependUrl: 'https://www.dewa.gov.ae/',
    articleListSelector: 'div.m8-teaser > a',
    articleHeaderSelector: 'h1.text__page-title',
    articleDateSelector: 'div.text__content-subcopy',
    articleTextSelector: 'div.m14-richtext > p',
    articleWriterSelector: '',
    hasWriter: false,
    hasHeader: true,
    hasDate: true,
  }
  // USING RSS FROM GOOGLE NEWS ALERT - The article sites have routing problem.
  // {
  //   url: 'http://www.empower.ae/news.php',
  //   articlePrependUrl: 'http://www.empower.ae/',
  //   articleListSelector: '#news > p > a',
  //   articleHeaderSelector: 'h3',
  //   articleDateSelector: 'i',
  //   articleTextSelector: 'div.col-lg-8.col-md-8.col-sm-8 p:nth-child(5)',
  //   articleWriterSelector: '',
  //   hasWriter: false,
  //   hasHeader: true,
  //   hasDate: true,
  // },
]